modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="SockyWocky"
description='''
Sorts create addons into tab sections under the main "Create" tab, reducing clutter and random tabs within the creative mode menu.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}-simulated.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="fancytabsections"
    type="required"
    versionRange="[5.0,6.0)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="simulated"
    type="optional"
    versionRange="[1.0,1.4)"
    ordering="AFTER"
    side="CLIENT"
